services:
  api:
    image: ghcr.io/engineer-man/piston
    container_name: hiresync-piston
    restart: always
    privileged: true
    ports:
      - '2000:2000'
    volumes:
      - piston_data:/piston
    networks:
      - piston-net

  runner:
    build:
      context: .
      dockerfile: apps/piston-runner/Dockerfile
    container_name: piston-runner
    restart: always
    ports:
      - '4000:4000'
    environment:
      - PISTON_INTERNAL_URL=http://api:2000
    depends_on:
      - api
    networks:
      - piston-net

volumes:
  piston_data:

networks:
  piston-net:
