-- AlterTable
ALTER TABLE "jobs" ADD COLUMN     "applicationDeadline" TIMESTAMP(3),
ADD COLUMN     "applicationDestination" TEXT,
ADD COLUMN     "applicationMethod" TEXT,
ADD COLUMN     "companyDescription" TEXT,
ADD COLUMN     "companyStage" TEXT,
ADD COLUMN     "culturePerks" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "department" TEXT,
ADD COLUMN     "domain" TEXT,
ADD COLUMN     "educationRequirement" TEXT DEFAULT 'not_required',
ADD COLUMN     "employmentType" TEXT NOT NULL DEFAULT 'full_time',
ADD COLUMN     "engagementDuration" TEXT,
ADD COLUMN     "experienceArea" TEXT,
ADD COLUMN     "experiencePreferred" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "experienceRequirement" TEXT NOT NULL DEFAULT 'not_required',
ADD COLUMN     "freshersPolicy" TEXT NOT NULL DEFAULT 'unspecified',
ADD COLUMN     "hybridDaysPerWeek" INTEGER,
ADD COLUMN     "jobLevel" TEXT,
ADD COLUMN     "keyResponsibilities" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "location" TEXT,
ADD COLUMN     "maxExperienceMonths" INTEGER,
ADD COLUMN     "minExperienceMonths" INTEGER,
ADD COLUMN     "numOpenings" INTEGER,
ADD COLUMN     "preferredSkills" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "preferredStartDate" TIMESTAMP(3),
ADD COLUMN     "preferredStartTimeframe" TEXT,
ADD COLUMN     "remoteEligibleLocations" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "requiredDegree" TEXT,
ADD COLUMN     "requiredField" TEXT,
ADD COLUMN     "requiredTechStack" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "roleCategory" TEXT,
ADD COLUMN     "salaryBasis" TEXT,
ADD COLUMN     "salaryCurrency" TEXT,
ADD COLUMN     "salaryMax" DECIMAL(12,2),
ADD COLUMN     "salaryMin" DECIMAL(12,2),
ADD COLUMN     "salaryPeriod" TEXT,
ADD COLUMN     "showSalary" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "whyJoin" TEXT,
ADD COLUMN     "workMode" TEXT NOT NULL DEFAULT 'onsite',
ADD COLUMN     "workingHours" TEXT,
ALTER COLUMN "skills" SET DEFAULT ARRAY[]::TEXT[];
